language: php
php:
  - 7.0
  - 7.1
  - hhvm

sudo: false

services:
  - mysql

before_install:
  - cp .env.travis .env
  - mysql -e 'create database social';
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit